### ISSUE TITLE
Does np.linalg.lstsq need to be called here?

### ISSUE THREAD

**Issue by petigura** [gjgilbert/alderaan#12]
I'm not sure why a linear ephemeris needs to be fit here. 

https://github.com/gjgilbert/alderaan/blob/cfae9c7e05c7df0a906e32aeedb90aadf050edad/alderaan/dynesty_helpers.py#L70-L75

t0 is set to zero a few lines later. the period is being fed into batman, but batman is just dealing with the wrapped times, so period is (I think) irrelevant.

**Comment by petigura** [comment]
the period argument is only relevant in batman if more than one transit is to be plotted, but for phase folded transits, there is no separation between them .

**Comment by gjgilbert** [comment]
Done
